= Neo4j on Docker Swarm

This is a first attempt at getting Neo4j 3.1 to run on Docker Swarm.

You can either setup Docker Swarm locally using link:https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm//[docker-machine] or on one of the cloud providers e.g. link:https://docs.docker.com/swarm/install-manual/[AWS]

Once you've got that setup you can run the following command to check that Docker Swarm is running:
e.g. on my machine

```
$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
5jj7tj4se6i2ppysenjrf9mm0 *  moby      Ready   Active        Leader
```

Before we install Neo4j we're going to create an overlay network which will make it easier to get our Neo4j servers to talk to each other:

```
docker network create --driver overlay --subnet 10.0.9.0/24 my-network
```

Let's check it got setup:

```
$ docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
...
bqb04faxdeks        my-network           overlay             swarm
...
```

Ok.
Now we're ready to install Neo4j.

== Core Servers

First let's install the Core servers.
We'd typically have a small number of Core servers in a cluster and they can handle both read and write traffic.

Run the following commands to create the Core servers:

```
$ docker service create \
    --replicas=3 \
    --network my-network \
    --name neo \
    -e NEO4J_AUTH=neo4j/neo \
    -e NEO4J_dbms_mode=CORE \
    -e NEO4J_causalClustering_expectedCoreClusterSize=3 \
    neo4j:3.1-enterprise \
    bash -c 'export NEO4J_dbms_connectors_defaultAdvertisedAddress=`hostname -f` && \
             export NEO4J_causalClustering_initialDiscoveryMembers=`nslookup tasks.neo 2>/dev/null | grep Address | cut -d " " -f3  | xargs -Iaddr echo addr:5000 | tr -s " " | cut -d " " -f 2 | tr "\n" "," | sed "s/,$//"` && \
             exec /docker-entrypoint.sh "neo4j"'
```

Docker exposes a special DNS name `tasks.<service-name>` (e.g. `tasks.neo`) which lets us access all our instances IPs.
We can then do an `nslookup` on that DNS name to get a list of those IPs and pass it to Neo4j as its initial discovery members.

Run the following command to see the servers we've just created:

```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                     NAMES
b18ac1962429        neo4j:3.1-enterprise   "/docker-entrypoint.s"   1 seconds ago       Up 5 seconds        7473-7474/tcp, 7687/tcp   neo.2.ck7vt7vteqg6s7k4fj3dn0t8e
04ffef90490e        neo4j:3.1-enterprise   "/docker-entrypoint.s"   1 seconds ago       Up 4 seconds        7473-7474/tcp, 7687/tcp   neo.3.34ekmywtqd3m2gu5qe5fin08t
7ebdabe05a1d        neo4j:3.1-enterprise   "/docker-entrypoint.s"   1 seconds ago       Up 5 seconds        7473-7474/tcp, 7687/tcp   neo.1.czizwameok2mk0om2t3gdoqtx
```

And we can check that Neo4j is up and running by running:

```
$ docker logs 04ffef90490e
Changed password for user 'neo4j'.
Starting Neo4j.
2016-12-12 15:30:28.106+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-12-12 15:30:29.066+0000 INFO  Starting...
2016-12-12 15:30:30.475+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2016-12-12 15:30:30.493+0000 INFO  Initiating metrics...
2016-12-12 15:30:30.634+0000 INFO  Waiting for other members to join cluster before continuing...
2016-12-12 15:31:20.904+0000 INFO  Started.
2016-12-12 15:31:21.050+0000 INFO  Mounted REST API at: /db/manage
2016-12-12 15:31:22.619+0000 INFO  Remote interface available at http://04ffef90490e:7474/
```

Neo4j also exposes the cluster topology via a procedure:

```
$ docker exec -it 04ffef90490e bash -c 'bin/cypher-shell --user=neo4j --password=neo "CALL dbms.cluster.overview()"'
id, addresses, role
"c50cfcbc-041a-4c05-9bdb-46ce89b53471", ["bolt://04ffef90490e:7687", "http://04ffef90490e:7474", "https://04ffef90490e:7473"], "FOLLOWER"
"11ef79d1-757e-4735-87ef-61e0333021ba", ["bolt://7ebdabe05a1d:7687", "http://7ebdabe05a1d:7474", "https://7ebdabe05a1d:7473"], "LEADER"
"8e138163-70e0-47b3-8c28-62bd668e784e", ["bolt://b18ac1962429:7687", "http://b18ac1962429:7474", "https://b18ac1962429:7473"], "FOLLOWER"

Bye!
```

== Read Replicas

Now that we've got the Core Servers up and running let's add some Read Replicas.
Read Replicas are used to scale out reads and they don't accept any write operations.

Run the following command to create a single Read Replica:

```
$ docker service create \
    --replicas=1 \
    --network my-network \
    --name neo-replica \
    -e NEO4J_AUTH=neo4j/neo \
    -e NEO4J_dbms_mode=READ_REPLICA \
    neo4j:3.1-enterprise \
    bash -c 'export NEO4J_dbms_connectors_defaultAdvertisedAddress=`hostname -f` && \
             export NEO4J_causalClustering_initialDiscoveryMembers=`nslookup tasks.neo 2>/dev/null | grep Address | cut -d " " -f3  | xargs -Iaddr echo addr:5000 | tr -s " " | cut -d " " -f 2 | tr "\n" "," | sed "s/,$//"` && \
             exec /docker-entrypoint.sh "neo4j"'
```

If we query for the list of containers now we'll see that it's been added to the list:

```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED                  STATUS                  PORTS                     NAMES
c4b55168227d        neo4j:3.1-enterprise   "/docker-entrypoint.s"   Less than a second ago   Up Less than a second   7473-7474/tcp, 7687/tcp   neo-replica.1.btiov5n8wotuy5x9v3vgtboxr
b18ac1962429        neo4j:3.1-enterprise   "/docker-entrypoint.s"   3 minutes ago            Up 3 minutes            7473-7474/tcp, 7687/tcp   neo.2.ck7vt7vteqg6s7k4fj3dn0t8e
04ffef90490e        neo4j:3.1-enterprise   "/docker-entrypoint.s"   3 minutes ago            Up 3 minutes            7473-7474/tcp, 7687/tcp   neo.3.34ekmywtqd3m2gu5qe5fin08t
7ebdabe05a1d        neo4j:3.1-enterprise   "/docker-entrypoint.s"   3 minutes ago            Up 3 minutes            7473-7474/tcp, 7687/tcp   neo.1.czizwameok2mk0om2t3gdoqtx
```

Let's check if the replica has joined the cluster and is ready to go:

```
$ docker logs c4b55168227d
Changed password for user 'neo4j'.
Starting Neo4j.
2016-12-12 15:34:05.043+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-12-12 15:34:05.509+0000 INFO  Starting...
2016-12-12 15:34:06.044+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2016-12-12 15:34:06.063+0000 INFO  Initiating metrics...
2016-12-12 15:34:12.021+0000 INFO  Started.
2016-12-12 15:34:12.169+0000 INFO  Mounted REST API at: /db/manage
2016-12-12 15:34:12.943+0000 INFO  Remote interface available at http://c4b55168227d:7474/
```

Yep, looks good!

Let's check that Neo4j knows about our new server:

```
$ docker exec -it 04ffef90490e bash -c 'bin/cypher-shell --user=neo4j --password=neo "CALL dbms.cluster.overview()"'
id, addresses, role
"c50cfcbc-041a-4c05-9bdb-46ce89b53471", ["bolt://04ffef90490e:7687", "http://04ffef90490e:7474", "https://04ffef90490e:7473"], "FOLLOWER"
"11ef79d1-757e-4735-87ef-61e0333021ba", ["bolt://7ebdabe05a1d:7687", "http://7ebdabe05a1d:7474", "https://7ebdabe05a1d:7473"], "LEADER"
"8e138163-70e0-47b3-8c28-62bd668e784e", ["bolt://b18ac1962429:7687", "http://b18ac1962429:7474", "https://b18ac1962429:7473"], "FOLLOWER"
"00000000-0000-0000-0000-000000000000", ["bolt://c4b55168227d:7687", "http://c4b55168227d:7474", "https://c4b55168227d:7473"], "READ_REPLICA"

Bye!
```

It does indeed.

Now let's scale up to 3 read replicas:

```
$ docker service scale neo-replica=3
neo-replica scaled to 3
```

And give it a few seconds and Neo4j will know about those servers as well:

```
$ docker exec -it 04ffef90490e bash -c 'bin/cypher-shell --user=neo4j --password=neo "CALL dbms.cluster.overview()"'
id, addresses, role
"c50cfcbc-041a-4c05-9bdb-46ce89b53471", ["bolt://04ffef90490e:7687", "http://04ffef90490e:7474", "https://04ffef90490e:7473"], "FOLLOWER"
"11ef79d1-757e-4735-87ef-61e0333021ba", ["bolt://7ebdabe05a1d:7687", "http://7ebdabe05a1d:7474", "https://7ebdabe05a1d:7473"], "LEADER"
"00000000-0000-0000-0000-000000000000", ["bolt://94b4944d0ea0:7687", "http://94b4944d0ea0:7474", "https://94b4944d0ea0:7473"], "READ_REPLICA"
"8e138163-70e0-47b3-8c28-62bd668e784e", ["bolt://b18ac1962429:7687", "http://b18ac1962429:7474", "https://b18ac1962429:7473"], "FOLLOWER"
"00000000-0000-0000-0000-000000000000", ["bolt://c4b55168227d:7687", "http://c4b55168227d:7474", "https://c4b55168227d:7473"], "READ_REPLICA"
"00000000-0000-0000-0000-000000000000", ["bolt://eafb950f4a02:7687", "http://eafb950f4a02:7474", "https://eafb950f4a02:7473"], "READ_REPLICA"

Bye!
```
